apiVersion: v1
kind: Service
metadata:
  name: ctis-web-service
  labels:
    run: my-nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ctis-web
