apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctis-web
  labels:
    app: ctis-web
spec:
  replicas: 1
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      app: ctis-web
  template:
    metadata:
      labels:
        app: ctis-web
        tier: web
    spec:
      containers:
      - name: ctis-web
        image: 859329449054.dkr.ecr.us-east-2.amazonaws.com/gov/usda/aphis/ppq/ctis-web:latest
        ports:
        - name: http
          containerPort: 80
